{-# LANGUAGE DeriveDataTypeable, NamedFieldPuns, RecordWildCards #-}

import Graphics.BarChart

import System.Console.CmdArgs
import Control.Monad ( when )

barChartConfig =
 conf { exec_mode =
         exec_mode conf `enum`
          [Default &= text "Generate multi-bar chart",
           IntervalBars &= text "Generate interval chart",
           MultiIntervalBars &= text "Generate multiple-interval chart",
           Criterion &= text "Parse data generated by criterion",
           Progression &= text "Parse data generated by progression"],
        out_file   = out_file conf &= text "Generated .png file",
        caption    = caption conf &= text "Title of bar chart",
        xlabel     = xlabel conf &= text "Label of x axis",
        ylabel     = xlabel conf &= text "Label of y axis",
        legend     = legend conf&=text "Labels for blocks in multi-bar charts",
        bar_colors = bar_colors conf &= text "Colors of blocks in bars",
        width      = width conf &= text "Width of generated bar chart",
        height     = height conf &= text "Height of generated bar chart",
        ratio      = ratio conf &= text "Changing this has no effect",
        font_size  = font_size conf &= text "Font size used for labels",
        bar_ratio  = bar_ratio conf &= text "Bar width / Bar distance",
        in_files   = in_files conf &= unknownFlags & text "Files to parse" }

main = do config@Config{..} <- cmdArgs "Bar-Chart v0.0" [mode barChartConfig]
          when (null in_files) (error "no input files given")
          let in_file : more_files = in_files
          case exec_mode of
            Default -> writeMultiBarChart config in_file (words legend)
            IntervalBars -> writeIntervalChart config in_file
            MultiIntervalBars ->
              writeMultiBarIntervalChart config in_file (words legend)
            Criterion | null more_files -> writeCriterionChart config in_file
                      | otherwise       -> writeComparisonChart config in_files
            Progression -> writeProgressionChart config in_file (words legend)
